Fix issue caused by dependency mismatch error
```
java.lang.NoSuchMethodError: 'int org.apache.commons.io.IOUtils.read(java.io.InputStream, byte[], int, int)'
```